"""Exports trained_policy.npz to a Dart source file containing the raw
weight matrices as literals, and a companion policy_inference.dart with the
forward pass hand-written (same math as policy.py's MLPActorCritic.forward,
argmax over logits — no stochastic sampling at deployment time).

Why not TFLite/ONNX: the network is 5 -> 32 -> 32 -> 4, small enough that a
conversion pipeline (torch -> ONNX -> TFLite) buys nothing but fragility —
one more native Flutter dependency to potentially fight with an AGP/compileSdk
mismatch, on top of bluetooth_classic and camera/ML Kit this session already
did. Plain Dart matrix multiplication is trivial to audit, has zero extra
dependencies, and is fast enough for a 5-dimensional input at whatever rate
you poll it.
"""
import numpy as np


def dart_matrix(name, arr):
    rows = arr.tolist()
    lines = ",\n    ".join("[" + ", ".join(f"{v:.6f}" for v in row) + "]" for row in rows) \
        if arr.ndim == 2 else ", ".join(f"{v:.6f}" for v in rows)
    if arr.ndim == 2:
        return f"const List<List<double>> {name} = [\n    {lines}\n  ];"
    return f"const List<double> {name} = [{lines}];"


def export(npz_path="trained_policy.npz", out_path="rover_policy_weights.dart"):
    data = np.load(npz_path)
    parts = [
        "// AUTO-GENERATED by export_dart.py — do not hand-edit.",
        "// Trained policy weights for the person-approach RL model.",
        "// See rover_rl/README.md for training methodology and known limitations",
        "// (residual close-range oscillation, ~25% timeout rate in eval — this is",
        "// not a solved/production-ready policy, treat it as a first working pass).",
        "",
        dart_matrix("W1", data["W1"]),
        dart_matrix("b1", data["b1"]),
        dart_matrix("W2", data["W2"]),
        dart_matrix("b2", data["b2"]),
        dart_matrix("Wp", data["Wp"]),
        dart_matrix("bp", data["bp"]),
        dart_matrix("Wv", data["Wv"]),
        dart_matrix("bv", data["bv"]),
    ]
    with open(out_path, "w") as f:
        f.write("\n\n".join(parts) + "\n")
    print(f"Wrote {out_path}")


if __name__ == "__main__":
    export()
